-- ÇÐ»ý Å×ÀÌºí »ý¼º
CREATE TABLE TB_STU(
    STU_NO NUMBER PRIMARY KEY,
    STD_NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(1),
    PHONE VARCHAR2(13),
    STU_STATUS VARCHAR2(10) DEFAULT 'ÀçÇÐ' CHECK(STU_STATUS 
    IN('ÀçÇÐ', 'ÅðÇÐ', 'Á¹¾÷', 'ÈÞÇÐ'))
);

-- ÇÐ¹ø ½ÃÄö½º »ý¼º
CREATE SEQUENCE SEQ_STU_NO
START WITH 900
INCREMENT BY 1;

DROP TABLE TB_STU;


-- ÈÞÇÐ Å×ÀÌºí »ý¼º
CREATE TABLE TB_ABSENCE(
    ABS_NO NUMBER PRIMARY KEY,
    STU_NO NUMBER REFERENCES TB_STU,
    ABS_DATE DATE,
    ABS_STATUS CHAR(1)
);

DROP TABLE TB_ABSENCE;

-- ÈÞÇÐ ½ÃÄö½º »ý¼º 
CREATE SEQUENCE SEQ_ABS_NO
START WITH 1
NOCACHE;

COMMIT;






CREATE OR REPLACE TRIGGER TRG_STU_01
AFTER UPDATE ON TB_STU -- AFTER UPDATE
FOR EACH ROW
BEGIN
    IF (:NEW.STU_STATUS = 'ÈÞÇÐ')
        THEN
           INSERT INTO TB_ABSENCE
           VALUES (SEQ_ABS_NO.NEXTVAL, :NEW.STU_NO, SYSDATE, 'Y');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_STU_04
AFTER INSERT ON TB_STU
FOR EACH ROW
BEGIN
    IF (:NEW.STU_STATUS = 'ÈÞÇÐ')
        THEN
            INSERT INTO TB_ABSENCE
            VALUES (SEQ_ABS_NO.NEXTVAL, :NEW.STU_NO, SYSDATE, 'Y');
        END IF;
END;
/




INSERT INTO TB_STU VALUES(SEQ_STU_NO.NEXTVAL, '±è½Ã¿¬', 'F', '01012314564','ÈÞÇÐ');


CREATE OR REPLACE TRIGGER TRG_STU_02
AFTER UPDATE ON TB_ABSENCE
FOR EACH ROW
BEGIN
    -- ÈÞÇÐ¿©ºÎ N
    IF (:NEW.ABS_STATUS = 'N')
        THEN
        UPDATE TB_STU
        SET STU_STATUS = 'ÀçÇÐ'
        WHERE STU_NO = :NEW.STU_NO;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_STU_01
AFTER UPDATE ON TB_STU
FOR EACH ROW
BEGIN
    IF (:NEW.STU_STATUS = 'Á¹¾÷')
        THEN
        DELETE FROM TB_STU
        WHERE STU_NO = :NEW.STU_NO;
    END IF;
END;
/


-- ÇÐ»ý Å×ÀÌºí µ¥ÀÌÅÍ
INSERT INTO TB_STU
VALUES(SEQ_STU_NO.NEXTVAL, '±èµÑ¸®', 'F', '01012345678', DEFAULT);

INSERT INTO TB_STU
VALUES(SEQ_STU_NO.NEXTVAL, '°í±æµ¿', 'M', '01045678900', 'Á¹¾÷');

INSERT INTO TB_STU
VALUES(SEQ_STU_NO.NEXTVAL, 'µµ¿ì³Ê', 'M', '01177886655', 'ÈÞÇÐ');

INSERT INTO TB_STU
VALUES(SEQ_STU_NO.NEXTVAL, '°­¶ÇÄ¡', 'F', '01155442233', 'ÈÞÇÐ');

INSERT INTO TB_STU
VALUES(SEQ_STU_NO.NEXTVAL, '¸¶ÀÌÄÝ', 'M', '01011447766', 'ÈÞÇÐ');

UPDATE TB_STU
SET STU_STATUS = 'ÈÞÇÐ'
WHERE STD_NAME = '±èµÑ¸®';
