-- 학생 테이블 생성
CREATE TABLE TB_STU(
    STU_NO NUMBER PRIMARY KEY,
    STD_NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(1),
    PHONE VARCHAR2(13),
    STU_STATUS VARCHAR2(10) DEFAULT '재학' CHECK(STU_STATUS 
    IN('재학', '퇴학', '졸업', '휴학'))
);

-- 학번 시퀀스 생성
CREATE SEQUENCE SEQ_STU_NO
START WITH 900
INCREMENT BY 1;

-- 학생 테이블 데이터
INSERT INTO TB_STU
VALUES(SEQ_STU_NO.NEXTVAL, '김둘리', 'F', '01012345678', DEFAULT);

INSERT INTO TB_STU
VALUES(SEQ_STU_NO.NEXTVAL, '고길동', 'M', '01045678900', '졸업');

INSERT INTO TB_STU
VALUES(SEQ_STU_NO.NEXTVAL, '도우너', 'M', '01177886655', '휴학');

INSERT INTO TB_STU
VALUES(SEQ_STU_NO.NEXTVAL, '강또치', 'F', '01155442233', '휴학');

INSERT INTO TB_STU
VALUES(SEQ_STU_NO.NEXTVAL, '마이콜', 'M', '01011447766', '휴학');

-- 휴학 테이블 생성
CREATE TABLE TB_ABSENCE(
    ABS_NO NUMBER PRIMARY KEY,
    STU_NO NUMBER REFERENCES TB_STU,
    ABS_DATE DATE,
    ABS_STATUS CHAR(1)
);





-- 휴학 시퀀스 생성 
CREATE SEQUENCE SEQ_ABS_NO
START WITH 1;




