SELECT *
FROM EMPLOYEE;

SELECT EMP_NAME, SALARY, HIRE_DATE, SALARY*12
FROM EMPLOYEE
WHERE SALARY >= 3000000;

SELECT EMP_NAME, SALARY, DEPT_CODE
FROM EMPLOYEE
WHERE SALARY * 12 >= 50000000;

SELECT EMP_NAME, SALARY, HIRE_DATE
FROM EMPLOYEE
WHERE EMP_NAME LIKE '전%';

SELECT EMP_NAME, EMP_NO, PHONE
FROM EMPLOYEE
WHERE EMP_NAME LIKE '%하%';

SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_NAME LIKE '_하_';

SELECT EMP_NAME, EMP_NO, PHONE, EMAIL
FROM EMPLOYEE
WHERE PHONE LIKE '__1%';

SELECT EMP_NO, EMP_NAME, EMAIL
FROM EMPLOYEE
WHERE EMAIL LIKE '___$_%' ESCAPE '$';

SELECT EMP_NO, EMP_NAME, EMAIL
FROM EMPLOYEE
WHERE NOT EMAIL LIKE '___$_%' ESCAPE '$';

SELECT *
FROM EMPLOYEE;

SELECT EMP_NAME, MANAGER_ID, DEPT_CODE
FROM EMPLOYEE
WHERE MANAGER_ID IS NULL AND DEPT_CODE IS NULL;

SELECT EMP_NAME, EMP_NO, SALARY, BONUS
FROM EMPLOYEE
WHERE SALARY*12 >= 30000000 AND BONUS IS NULL;

SELECT EMP_ID, EMP_NAME, HIRE_DATE, DEPT_CODE
FROM EMPLOYEE
WHERE HIRE_DATE >= '95/01/01' AND DEPT_CODE IS NOT NULL;

SELECT EMP_ID, EMP_NAME, SALARY, HIRE_DATE, BONUS
FROM EMPLOYEE
WHERE SALARY >= 2000000 AND SALARY <= 5000000 AND HIRE_DATE >= '01/01/01' AND BONUS IS NULL;

SELECT EMP_ID AS "사번", EMP_NAME AS "이름", SALARY AS "급여", (SALARY + (SALARY * BONUS)) * 12 AS "보너스포함연봉"
FROM EMPLOYEE
WHERE (SALARY + (SALARY * BONUS)) IS NOT NULL AND EMP_NAME LIKE '%하%';

SELECT EMP_NAME, SALARY * 12
FROM EMPLOYEE
ORDER BY SALARY * 12 DESC;

SELECT EMP_NAME, SALARY
FROM EMPLOYEE
ORDER BY SALARY ASC;

SELECT SYSDATE FROM DUAL;

SELECT LENGTH('오라클') FROM DUAL;

SELECT LENGTHB('ORACLE') FROM DUAL;

SELECT INSTR('AABAACAABBAA', 'B') FROM DUAL;

SELECT EMP_NAME, EMAIL, INSTR(EMAIL, '@') FROM EMPLOYEE;

SELECT INSTR('AABAACAABBAA', 'B', -1) FROM DUAL;

SELECT INSTR('AABAACAABBAA', 'B', 2) FROM DUAL;

SELECT EMAIL, INSTR(EMAIL, '_', 1, 1) AS "_위치", INSTR(EMAIL, '@') AS "골뱅이 위치"
FROM EMPLOYEE;

SELECT SUBSTR('SHOWMETHEMONEY', 7,2) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY', -8) FROM DUAL;

SELECT EMP_NAME
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 8, 1) = '2';

SELECT EMP_NAME, EMP_NO
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 8, 1) = '1';

SELECT EMP_NAME, EMAIL, SUBSTR(EMAIL, 1, INSTR(EMAIL, '@') - 1) AS "아이디"
FROM EMPLOYEE;

SELECT EMP_NAME, LPAD(EMAIL, 20) FROM EMPLOYEE;

SELECT EMP_NAME, RPAD(EMAIL, 20, '#') FROM EMPLOYEE;

SELECT EMP_NAME, RPAD(SUBSTR(EMP_NO, 1, 8), 14, '*') FROM EMPLOYEE;

SELECT LTRIM('   K  H   ') FROM DUAL;
SELECT RTRIM('   K  H   ') FROM DUAL;

SELECT LTRIM('123123KH123', '123') FROM DUAL;
SELECT LTRIM('ACABACCKH', 'ABC') FROM DUAL;

SELECT RTRIM('5782KH123', '0123456789') FROM DUAL;
SELECT TRIM('   K H   ')FROM DUAL;
SELECT TRIM('Z' FROM 'ZZZKHZZZ') FROM DUAL;
SELECT TRIM(LEADING 'Z' FROM 'ZZZKHZZZ') FROM DUAL;

SELECT LOWER('Welcome To My World!') FROM DUAL;
SELECT UPPER('Welcome To My World!') FROM DUAL;
SELECT INITCAP('welcome to my world!') FROM DUAL;

SELECT CONCAT('ABC', 'CHOCOLATE')FROM DUAL;
SELECT 'ABC' || 'CHOCOLATE' FROM DUAL;