
CREATE TABLE FRIENDS(
    FRI_ID NUMBER ,
    FRI_NAME VARCHAR2(20) CONSTRAINT FR_NAM NOT NULL,
    FRI_GENDER CHAR(3) CONSTRAINT FR_GEN CHECK(FRI_GENDER IN ('남', '여')),
    FRI_ADDRESS VARCHAR2(50) CONSTRAINT FR_ADR NOT NULL,
    FRI_NATION VARCHAR2(20) CONSTRAINT FR_NAT NOT NULL,
    FRI_PHONE VARCHAR2(15),
    FRI_BDAY DATE,
    PRIMARY KEY(FRI_ID, FRI_NAME)  
);

DROP TABLE FRIENDS;

SELECT * FROM FRIENDS;

INSERT INTO FRIENDS
VALUES(1, '신짱구', '남', '떡잎마을', '한국', '010-5555-5555',  '1994/5/5');

INSERT INTO FRIENDS
VALUES(2, '오동동', '남', '뉴욕', '미국', '818-510-7409', '1994/1/11');

INSERT INTO FRIENDS
VALUES(3, '신태일', '남', '도쿄', '일본', '080-1234-5678', NULL);

INSERT INTO FRIENDS
VALUES(4, '보노보노', '남', '누크', '그린란드', '010-6303-4682', '1995/9/20');

INSERT INTO FRIENDS
VALUES(5, '호날두', '남', '마데이라', '포르투갈', '010-7777-7777', '1985/2/5');

COMMENT ON COLUMN FRIENDS.FRI_ID IS '순번';
COMMENT ON COLUMN FRIENDS.FRI_NAME IS '이름';
COMMENT ON COLUMN FRIENDS.FRI_GENDER IS '성별';
COMMENT ON COLUMN FRIENDS.FRI_ADDRESS IS '주소';
COMMENT ON COLUMN FRIENDS.FRI_NATION IS '국적';
COMMENT ON COLUMN FRIENDS.FRI_BDAY IS '생일';
COMMENT ON COLUMN FRIENDS.FRI_PHONE IS '전화번호';

CREATE TABLE GF(
   GF_ID NUMBER,
   GF_NAME VARCHAR2(20),
   GF_SPIECIES VARCHAR2(20),
   PRIMARY KEY(GF_ID)
);

DROP TABLE GF;

SELECT * FROM GF;

INSERT INTO GF
VALUES(1, '한수지', '2D');

INSERT INTO GF
VALUES(2, NULL, NULL);

INSERT INTO GF
VALUES(3, '아구몬','디지몬');

INSERT INTO GF
VALUES(4, '너부리','동물');

INSERT INTO GF
VALUES(5, '메시','사람');

SELECT FRI_NAME, GF_NAME FROM FRIENDS, GF
WHERE FRI_ID = GF_ID;

SELECT FRI_NAME 이름, FRI_ADDRESS 주소, 
FRI_BDAY 생일, NVL(GF_NAME, '파트너 없음') 파트너, NVL(GF_SPIECIES, '파트너 없음') 파트너종족
FROM FRIENDS
JOIN GF ON (FRI_ID = GF_ID)
--WHERE EXTRACT(YEAR FROM (FRI_BDAY)) = '1994';
WHERE NOT GF_NAME IS NULL;





