
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '이상해씨','풀', '씨앗포켓몬', 0.7, 6.9, '태어나서부터 얼마 동안은 등의 씨앗으로부터 영양을 공급받아 크게 성장한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '이상해풀','풀', '씨앗포켓몬', 1, 13, '등의 봉오리가 부풀어 오르면 달콤한 냄새가 감돌기 시작한다. 큰 꽃이 필 조짐이다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '이상해꽃','풀', '씨앗포켓몬', 2, 100, '비가 내린 다음 날은 등의 꽃향기가 강해진다. 향기에 이끌려 포켓몬이 모여든다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '파이리','불꽃', '도롱뇽포켓몬', 0.6, 8.5, '파이리 꼬리의 불꽃은 생명의 등불이다. 건강할 때는 불꽃도 강하게 타오른다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '리자드','불꽃', '화염포켓몬', 1.1, 19, '리자드가 사는 바위산을 한밤중에 올려다보면 꼬리의 불꽃이 별처럼 보인다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '리자몽','불꽃, 비행',	'화염포켓몬', 1.7, 90.5, '힘든 싸움을 경험한 리자몽일수록 불꽃 온도가 높아진다고 전해진다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '꼬부기','물',	'꼬마거북포켓몬', 0.5, 9, '등껍질에 숨어 몸을 보호한다. 상대의 빈틈을 놓치지 않고 물을 뿜어내어 반격한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '어니부기', '물', '거북포켓몬', 1, 22.5, '만 년의 수명을 가지고 있다고 전해진다. 치렁치렁한 꼬리는 장수의 상징으로서 인기가 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '거북왕', '물', '껍질포켓몬', 1.6, 85.5, '등껍질의 로켓포로부터 뿜어내는 물줄기는 두꺼운 철판도 한 번에 꿰뚫는 파괴력이 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '캐터피', '벌레', '애벌레포켓몬', 0.3,	2.9, '빨간 더듬이로부터 냄새를 내어 상대를 쫓아 버린다. 탈피를 반복하여 자라난다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '단데기', '벌레', '번데기포켓몬', 0.7,	9.9, '강철같이 단단한 껍질로 부드러운 몸을 보호하고 있다. 진화할 때까지 가만히 참고 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '버터플', '벌레, 비행', '나비포켓몬', 1.1, 32, '꽃의 꿀을 매우 좋아한다. 약간의 꽃가루만으로 꽃밭이 있는 장소를 찾아낼 수 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '뿔충이', '벌레, 독', '송충이포켓몬', 0.3, 3.2, '매일 자신과 똑같은 무게의 잎사귀를 먹는다. 머리의 침으로 달려드는 상대를 물리친다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '딱충이', '벌레, 독', '번데기포켓몬', 0.6, 10, '천적에게 발견되지 않도록 잎사귀 뒷면이나 가지의 틈새에 숨어서 진화할 때를 기다린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '독침붕', '벌레, 독', '독벌포켓몬', 1, 29.5, '고속으로 날아다니며 독침으로 공격한 뒤 바로 날아가 버리는 전법이 특기다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '구구', '노말, 비행', '아기새포켓몬', 1, 29.5, '싸움을 좋아하지 않는 얌전한 성격이지만 어설프게 건드리면 강력한 반격을 당하게 된다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '피죤', '노말, 비행', '새포켓몬', 1.1, 30, '넓은 영역을 날아다니며 먹이를 찾는다. 발달한 발톱으로 먹이를 꼼짝 못 하게 한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '피죤투', '노말, 비행', '새포켓몬', 1.5, 39.5, '피죤투의 힘찬 날갯짓은 큰 나무도 휠 정도의 강풍을 일으킨다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '꼬렛', '노말', '쥐포켓몬', 0.3, 3.5, '어떤 장소에도 정착하여 살아갈 수 있는 생명력이 있다. 경계심이 매우 강하다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '레트라', '노말', '쥐포켓몬', 0.7, 18.5, '계속 자라는 앞니를 갈아 내려고 딱딱한 것을 갉는 습성이 있다. 벽돌로 된 벽도 갉아서 부순다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '깨비참', '노말, 비행', '아기새포켓몬', 0.3, 2, '작은 날개를 쉴 새 없이 파닥여 날아오른다. 풀밭에 있는 먹이를 부리로 찾아낸다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '깨비드릴조', '노말, 비행', '부리포켓몬', 1.2, 38, '큰 날개로 온종일 날아다닐 수 있는 체력의 소유자다. 날카로운 부리로 싸운다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '아보', '독', '뱀포켓몬', 2, 6.9, '소리를 전혀 내지 않고 풀밭 속을 나아간다. 방심하고 있는 먹이를 배후에서 덮친다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '아보크', '독', '코브라포켓몬', 3.5, 65, '배의 무늬로 상대를 위협한다. 무늬에 겁을 먹고 움직일 수 없게 된 사이에 몸으로 조인다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '피카츄', '전기', '쥐포켓몬', 0.4, 6, '숲속에서 동료와 산다. 볼의 양쪽에 있는 전기 주머니에 전기를 모아 둔다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '라이츄', '전기', '쥐포켓몬', 0.8, 30, '몸의 전기가 지나치게 축적되면 공격적인 성향을 지니게 된다. 꼬리로부터 전기를 흘려보낸다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '모래두지', '땅', '쥐포켓몬', 0.6, 12, '비가 거의 내리지 않는 건조한 토지에 서식한다. 몸을 둥글게 말아서 자신을 보호한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '고지', '땅', '쥐포켓몬', 1, 29.5,'몸을 둥글게 말아서 등으로 몸통박치기한다. 날카로운 가시들이 큰 데미지를 준다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '니드런(여)', '독', '독침포켓몬', 0.4, 7, '싸움을 좋아하지 않는 성격이다. 독침에서 분비된 독은 한 방울만 맞아도 생명을 빼앗긴다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '니드리나', '독', '독침포켓몬', 0.8, 20, '위험을 느끼면 전신의 가시를 곤두세운다. 니드리노에 비해서 가시의 성장이 느리다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '니드퀸', '독, 땅', '드릴포켓몬', 1.3, 60, '갑옷처럼 단단한 비늘이 전신을 둘러싼다. 둥지의 새끼를 목숨 걸고 지킨다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '니드런(남)', '독', '독침포켓몬', 0.5, 9, '풀밭 위로 귀만 내놓고 주위의 낌새를 살핀다. 맹독의 뿔로 몸을 보호한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '니드리노', '독', '독침포켓몬', 0.9, 19.5, '기질이 거친 포켓몬이다. 상대를 깊이 찌른 충격으로 뿔에서 맹독이 배어 나온다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '니드킹', '독, 땅', '드릴포켓몬', 1.4, 62, '꼬리를 한 번 휘두르면 전신주를 성냥개비마냥 두 동강 내 버린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '삐삐', '페어리', '요정포켓몬', 0.6, 7.5, '귀여운 표정과 동작으로 인기가 많다. 조용한 산속에서 동료들과 사는 것으로 여겨지고 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '픽시', '페어리', '요정포켓몬', 1.3, 40, '거의 모습을 드러내지 않는다. 보름달에 이끌려 인적 없는 호수에서 논다고 전해진다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '식스테일', '불꽃', '여우포켓몬', 0.6, 9.9, '불꽃의 구슬을 조종한다. 성장하면 6개의 꼬리는 끝이 갈라져서 한층 더 늘어난다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '나인테일', '불꽃', '여우포켓몬', 1.1, 19.9, '9개의 꼬리에는 신비한 힘이 깃들어 있다고 전해진다. 천 년을 살 수 있는 듯하다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '푸린', '노말, 페어리', '풍선포켓몬', 0.5, 5.5, '동그란 눈동자가 흔들릴 때 누구나 잠이 오게 되는 자장가를 부르기 시작한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '푸크린', '노말, 페어리', '풍선포켓몬', 1, 12, '세밀한 털은 결이 매우 고와 감촉이 최고로 좋다. 숨을 들이마셔서 몸을 부풀린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '주뱃', '독, 비행', '박쥐포켓몬', 0.8, 7.5,'입에서 내는 초음파로 두 눈이 없어도 주위의 장애물을 탐색할 수 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '골뱃', '독, 비행', '박쥐포켓몬', 1.6, 55,'사람이나 포켓몬의 혈액을 매우 좋아한다. 목덜미의 혈관을 노리며 밤하늘을 날아다닌다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '뚜벅쵸', '풀, 독', '잡초포켓몬', 0.5, 5.4,'낮에는 뿌리인 발을 땅에 박고 움직이지 않을 때가 많다. 밤에 돌아다니며 씨를 뿌린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '냄새꼬', '풀, 독', '잡초포켓몬', 0.8, 8.6,'입에서 흘러내리는 꿀은 2km 떨어져 있어도 머리가 아플 정도로 심한 악취가 난다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '라플레시아', '풀, 독','꽃포켓몬', 1.2, 18.6, '세계에서 꽃잎이 제일 크다. 심한 알레르기를 일으킬 독 꽃가루를 흩뿌리며 걷는다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '파라스', '벌레, 풀', '버섯포켓몬', 0.3, 5.4, '동충하초라고 불리는 버섯을 등에 기르고 있다. 파라스와 함께 크게 자란다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '파라섹트', '벌레, 풀', '버섯포켓몬', 1, 29.5, '몸보다 큰 버섯이 파라섹트를 조종하고 있다. 독 포자를 여기저기 뿌린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '콘팡', '벌레, 독', '곤충포켓몬', 1, 30, '작은 눈이 많이 모여 큰 눈을 이루고 있다. 밤이 되면 불빛을 향해 모여든다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '도나리', '벌레, 독', '독나방포켓몬', 1.5, 12.5, '날갯짓으로 인분을 흩뿌린다. 인분이 몸에 붙으면 독 성분이 피부에 스며든다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '디그다', '땅', '두더지포켓몬', 0.2, 0.8, '땅속에서 살고 있는 포켓몬이다. 어두운 지하에 있기 때문에 밝은 태양을 싫어한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '닥트리오', '땅', '두더지포켓몬', 0.7, 33.3, '3개의 머리가 교차하며 움직여서 아무리 딱딱한 지층이라도 지하 100km까지 파 내려간다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '나옹', '노말', '요괴고양이포켓몬', 0.4, 4.2, '한밤중에 움직이는 습성이 있다. 반짝반짝 빛나는 것을 발견하면 그에 못지않게 눈동자가 반짝인다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '페르시온', '노말', '샴고양이포켓몬', 1, 32, '자존심이 센 포켓몬이다. 마니아 사이에서는 이마의 보석 크기가 화제가 된다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '고라파덕', '물', '오리포켓몬', 0.8, 19.6,'두통이 심해지면 이상한 힘을 사용하게 된다. 그때의 일은 기억하지 못한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '골덕', '물', '오리포켓몬', 1.7, 76.6,'호수에 사는 포켓몬이다. 헤엄치는 스피드는 내로라하는 수영 선수보다도 빠르다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '망키', '격투', '돈숭이포켓몬', 0.5, 28, '나무 위에서 생활하고 있다. 무리 중 1마리가 화내기 시작하면 모두 아무 의미도 없이 난동을 부린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '성원숭', '격투', '돈숭이포켓몬', 1, 32, '시선을 마주치기만 해도 화내고 도망치면 또 화내고 때려눕혀도 계속 화를 낸다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '가디', '불꽃', '강아지포켓몬', 0.7, 19, '충실한 성격의 포켓몬이다. 트레이너의 명령이 있기 전까진 한 발짝도 움직이지 않는다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '윈디', '불꽃', '전설포켓몬', 1.9, 155, '위풍당당한 모습은 오래전부터 사람들의 마음을 사로잡아 왔다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '발챙이', '물', '올챙이포켓몬', 0.6, 12.4, '내장이 들여다보일 정도로 피부가 얇다. 갓 자란 다리로 서툴게 걷는다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '슈륙챙이', '물', '올챙이포켓몬', 1, 20, '배의 소용돌이는 미묘하게 꾸불거리므로 바라보고 있으면 점점 잠이 오게 된다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '강챙이', '물, 격투', '올챙이포켓몬', 1.3, 54, '강인한 근육을 가지고 있다. 태평양을 쉬지 않고 계속 헤엄칠 수 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '캐이시', '에스퍼', '초능력포켓몬', 0.9, 19.5, '매일 18시간을 잠잔다. 깨어 있을 때도 앉은 채 순간이동으로 이동한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '윤겔라', '에스퍼', '초능력포켓몬', 1.3, 56.5, '윤겔라가 옆에 있으면 TV에 이상한 그림자가 비친다. 그것을 보면 불행해진다고 전해진다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '후딘', '에스퍼', '초능력포켓몬', 1.5, 48, '태어나서부터 체험한 모든 것을 기억하고 있을 정도의 기억력을 가지고 있다. IQ가 5000이 넘는다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '알통몬', '격투', '괴력포켓몬', 0.8, 19.5, '데구리를 수없이 들었다 놨다 하며 전신의 근육을 단련한다. 모든 격투기를 사용한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '근육몬', '격투', '괴력포켓몬', 1.5, 70.5, '근육몬의 끝없는 파워는 매우 위험하므로 힘을 제어하는 벨트를 차고 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '괴력몬', '격투', '괴력포켓몬', 1.6, 130, '4개의 팔을 눈에 보이지 않을 정도로 빠르게 움직여 2초간 1000발의 펀치를 날린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '모다피', '풀, 독', '꽃포켓몬', 0.7, 4, '온다습한 땅을 좋아한다. 덩굴을 뻗어서 먹이를 잡을 때의 움직임은 매우 재빠르다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '우츠동', '풀, 독', '파리잡이포켓몬', 1, 6.4, '식물과 똑 닮은 포켓몬이다. 방심해서 가까이 다가온 먹이에게 독가루를 뿌려서 잡는다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '우츠보트', '풀, 독', '파리잡이포켓몬', 1.7, 15.5, '꿀 같은 향기의 액체를 입에 모아 두고 있지만 그것은 무엇이든 녹이는 용해액이다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '왕눈해', '물, 독', '해파리포켓몬', 0.9, 45.5, '몸 대부분이 수분이다. 수정 같은 눈에서 이상한 빔을 발사한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '독파리', '물, 독', '해파리포켓몬', 1.6, 55, '80개의 촉수를 가지고 있다. 먹이를 붙잡으면 독으로 인해 약해질 때까지 절대 놓치지 않는다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '꼬마돌', '바위, 땅', '암석포켓몬', 0.4, 20, '산길에 많이 서식한다. 몸의 절반을 땅에 묻고 등산하는 사람들의 모습을 바라본다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '데구리', '바위, 땅', '암석포켓몬', 1, 105, '험한 절벽의 중턱에 몇 개의 구멍이 보인다면 그곳은 데구리의 거처이다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '딱구리', '바위, 땅', '메가톤포켓몬', 1.4, 300, '1년에 1번 탈피한다. 암석 같은 단단한 몸은 다이너마이트로도 상처를 입힐 수 없다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '포니타', '불꽃', '불의말포켓몬', 1, 30, '태어나서 1시간이 지나면 불꽃의 갈기와 꼬리가 자라나 멋진 모습이 된다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '날쌩마', '불꽃', '불의말포켓몬', 1.7, 95, '달리는 속도는 시속 240km. 갈기의 불꽃이 세차게 타오르고 화살처럼 달려 나간다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '야돈', '물, 에스퍼', '얼간이포켓몬', 1.2, 36, '움직임은 느리지만 꼬리를 사용하는 낚시가 특기다. 둔감하므로 꼬리를 물려도 아프지 않다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '야도란', '물, 에스퍼', '기생포켓몬', 1.6, 78.5, '멍하게 있는 야도란이지만 셀러가 강하게 꼬리를 물 때 무언가가 번뜩이는 듯하다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '코일', '전기, 강철', '자석포켓몬', 0.3, 6, '좌우의 유닛에서 전기자석파를 내어 공중을 이동한다. 전기를 먹는 포켓몬이다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '레어코일', '전기, 강철', '자석포켓몬', 1, 60, '3마리의 코일이 자력으로 연결된 포켓몬이다. 레어코일이 늘어나면 자기 폭풍이 일어난다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '파오리', '노말, 비행', '청둥오리포켓몬', 0.8, 15, '파 줄기가 없으면 살 수 없다. 그래서 파 줄기를 노리는 상대와는 목숨을 걸고 싸운다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '두두', '노말, 비행', '쌍둥이새포켓몬', 1.4, 39.2, '두 머리에 각각 존재하는 뇌는 텔레파시 같은 힘으로 의사를 맞춰 나가는 듯하다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '두트리오', '노말, 비행', '세쌍둥이새포켓몬', 1.8, 85.2, '진화할 때 두두의 머리 중 한쪽이 분열되는 희귀종. 시속 60km 이상으로 달린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '쥬쥬', '물', '강치포켓몬', 1.1, 90, '빙산에 사는 포켓몬이다. 머리의 뾰족하게 돌출된 부분으로 얼음을 깨고 바다를 헤엄친다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '쥬레곤', '물, 얼음', '강치포켓몬', 1.7, 120, '전신이 새하얀 털로 덮여 있기 때문에 눈 속에서는 천적에게 발견되지 않는다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '질퍽이', '독', '진흙포켓몬', 0.9, 30, '시궁창의 진흙이 달로부터의 X선을 쬐어 태어났다. 더러운 장소에서 나타난다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '질뻐기', '독', '진흙포켓몬', 1.2, 30, '몸에서 맹독의 체액이 배어 나오고 있다. 그 액에 스친 초목은 순식간에 시든다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '셀러', '물', '두조개포켓몬', 0.3, 4, '2장의 껍질을 여닫아서 뒤쪽으로 헤엄친다. 어떤 때든 큰 혀는 항상 내어놓는다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '파르셀', '물, 얼음', '두조개포켓몬', 1.5, 132.5, '껍질을 잘 닫아 몸을 보호하면서 가시를 날려 상대를 물리치는 전법을 쓴다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '고오스', '고스트, 독', '가스포켓몬', 1.3, 0.1, '몸의 95퍼센트가 가스로 이루어진 포켓몬이다. 강풍에 날려가 버린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '고우스트', '고스트, 독', '가스포켓몬', 1.6, 0.1, '어떤 장애물도 빠져나갈 수 있다. 벽 속에 숨어들어 상대의 모습을 관찰한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '팬텀', '고스트, 독', '그림자포켓몬', 1.5, 40.5, '그림자에 모습을 숨긴다. 팬텀이 숨어 있는 방은 온도가 5도 내려간다고 전해진다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '롱스톤', '바위, 땅', '돌뱀포켓몬', 8.8, 210, '롱스톤이 땅속을 뚫고 나아가면 땅울림이 들리며 지면이 흔들린다. 이동 속도는 시속 80km.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '슬리프', '에스퍼', '최면포켓몬', 1, 32.4, '튀어나온 코를 실룩샐룩하면 꾸고 있는 꿈을 안다고 한다. 즐거운 꿈을 매우 좋아한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '슬리퍼', '에스퍼', '최면포켓몬', 1.6, 75.6, '눈앞에서 추를 흔들면 방금 깨어난 사람도 3초 후에는 잠들어 버린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '크랩', '물', '게포켓몬', 0.4, 6.5, '모래 해변에 구멍을 파서 산다. 집게는 싸울 때 떨어져 나가도 다시 자라나 원래대로 돌아온다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '킹크랩', '물', '집게포켓몬', 1.3, 60, '큰 집게의 파워는 1만 마력이다. 하지만 너무 무거워서 목표물을 잡는 것이 서투르다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '찌리리공', '전기', '볼포켓몬', 0.5, 10.4, '몬스터볼과 똑 닮았다. 잘못해서 만지면 감전되거나 때로는 폭발하므로 위험하다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '붐볼', '전기', '볼포켓몬', 1.2, 66.6, '전기 에너지를 너무 모아서 팽팽히 부풀어 오른 붐볼이 바람에 날려 오는 경우가 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '아라리', '풀, 에스퍼', '알포켓몬', 0.4, 2.5, '텔레파시로 대화를 하기 때문에 아라리를 갈라놓으려 해도 바로 모여들어 6마리가 된다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '나시', '풀, 에스퍼', '야자열매포켓몬', 2, 120, '걸어 다니는 열대 우림이라고 불린다. 크게 자란 머리 중 하나가 땅에 떨어지면 아라리가 된다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '탕구리', '땅', '고독포켓몬', 0.4, 6.5, '사별한 어머니를 생각하며 울 때에는 머리에 쓴 뼈가 달각달각 소리를 낸다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '텅구리', '땅', '뼈다귀포켓몬', 1, 45, '태어날 때부터 항상 지니고 있는 뼈를 자유로이 사용한다. 성격은 난폭하다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '시라소몬', '격투', '킥포켓몬', 1.5, 49.8, '다리가 두 배 길이로 늘어난다. 처음 싸운 상대는 그 길이에 놀란다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '홍수몬', '격투', '펀치포켓몬', 1.4, 50.2, '팔을 비틀며 날리는 펀치는 콘크리트도 부스러뜨린다. 3분 싸우면 잠시 쉰다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '내루미', '노말', '핥기포켓몬', 1.2, 65.5, '손 대신 신장의 2배로 늘어나는 혓바닥을 사용한다. 끈적끈적한 타액이 무엇이든 달라붙게 한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '또가스', '독', '독가스포켓몬', 0.6, 1, '공기보다도 가벼운 가스를 몸에 모아서 떠 있다. 가스는 냄새나는 데다가 폭발도 한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '또도가스', '독', '독가스포켓몬', 1.2, 9.5, '쓰레기에서 발생한 가스를 먹고 자라난다. 극히 드물게 3개가 이어진 또도가스가 발견된다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '뿔카노', '땅, 바위', '뿔포켓몬', 1, 115, '몸이 단단한 피부로 덮여 있다. 몸통박치기로 빌딩도 쓰러뜨린다. 안타깝게도 머리는 나쁘다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '코뿌리', '땅, 바위', '드릴포켓몬', 1.9, 120, '뒷발로 서게 되어 뇌가 커졌다. 드릴로 된 뿔로 바위를 뚫어 터널을 판다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '럭키', '노말', '알포켓몬', 1.1, 34.6, '행복을 가져다준다고 전해진다. 상처 입은 사람에게 알을 나눠 주는 상냥한 포켓몬이다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '덩쿠리', '풀', '넝쿨포켓몬', 1, 35, '파란 덩굴로 덮여 있다. 덩굴에 숨겨져 있는 얼굴을 본 사람은 아직 없다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '캥카', '노말', '가족포켓몬', 2.2, 80, '배의 주머니에서 새끼를 키운다. 안전할 때만 새끼를 주머니에서 꺼내어 놀게 한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '쏘드라', '물', '드래곤포켓몬', 0.4, 8, '산호의 그늘에 거처를 만든다. 위험을 느끼면 입에서 새까만 먹물을 내뿜고 도망간다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '시드라', '물', '드래곤포켓몬', 1.2, 25, '가시가 상대로부터 몸을 지킨다. 지느러미와 뼈가 한약의 재료로써 귀하게 쓰인다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '콘치', '물', '금붕어포켓몬', 0.6, 15, '꼬리지느러미를 드레스같이 흔들며 우아하게 헤엄치는 모습은 마치 수중의 여왕 같다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '왕콘치', '물', '금붕어포켓몬', 1.3, 39, '머리의 뿔로 강바닥에 있는 돌을 파내어 둥지를 만든다. 알을 목숨 걸고 지킨다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '별가사리', '물', '별포켓몬', 0.8, 34.5, '빨간 핵이 있는 한, 몸이 조각나도 바로 재생한다. 한밤중에 핵이 반짝거린다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '아쿠스타', '물, 에스퍼', '수수께끼포켓몬', 1.1, 80, '몸의 중심에 있는 빨간 핵에서 밤하늘을 향해 알 수 없는 전파를 발신한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '마임맨', '에스퍼, 페어리', '배리어포켓몬', 1.3, 54.5, '팬터마임의 달인이다. 손짓 발짓으로 만든 벽은 이윽고 진짜 벽이 된다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '스라크', '벌레, 비행', '버마재비포켓몬',  1.5, 56, '양팔의 낫에 의한 공격을 막는 것은 불가능에 가깝다. 그 움직임은 마치 닌자 같다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '루주라', '얼음', '인간형태포켓몬', 1.4, 40.6, '울음소리는 마치 인간의 말처럼 들리지만 의미는 전혀 이해할 수 없다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '에레브', '전기', '전기포켓몬', 1.1, 30, '정전이 일어나는 원인의 절반은 에레브가 발전소에 나타나 전기를 먹어 버린 탓이다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '마그마', '불꽃', '불뿜기포켓몬', 1.3, 44.5, '화산의 분화구에서 태어나 자랐다. 태양과도 같은 불꽃의 일렁임이 전신을 감싼다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '쁘사이저', '벌레', '뿔집게포켓몬', 1.5, 55, '2개의 뿔 사이에 먹이를 끼우고 조각날 때까지 놓지 않는다. 조각나지 않으면 저편으로 세게 내던진다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '켄타로스', '노말', '성난소포켓몬', 1.4, 88.4, '노리는 먹이를 포착하면 일직선으로 돌진한다. 난폭한 성격으로 유명하다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '잉어킹', '물', '물고기포켓몬', 0.9, 10, '세상에서 제일 약하다고 전해지는 잉어킹이 어떻게 살아남아 있는지 아무도 모른다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '갸라도스', '물', '흉악포켓몬', 6.5, 235, '한번 모습을 나타내면 산과 들의 모든 것을 다 태워 버리기 전까지 분노가 가라앉지 않는다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '라프라스', '물, 얼음', '탈것포켓몬', 2.5, 220, '사람이나 포켓몬을 등에 태워 바다를 건너는 것을 매우 좋아한다. 사람의 말을 이해할 수 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '이브이', '노말', '진화포켓몬', 0.3, 4, '진화할 때 모습과 능력이 바뀜으로써 혹독한 환경에 적응하는 희귀한 포켓몬이다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '메타몽', '노말', '변신포켓몬', 0.3, 6.5, '전신의 세포를 재구성해서 본 것의 모양과 똑 닮게 변신하는 능력을 가지고 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '샤미드', '물', '거품뿜기포켓몬', 1, 29, '수중에서의 생활에 적합한 몸으로 진화했다. 물에 녹아들면 보이지 않게 된다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '쥬피썬더', '전기', '번개포켓몬', 0.8, 24.5, '1만 볼트의 전기를 다룬다. 전신의 털이 곤두서면 바늘같이 날카롭고 뾰족해진다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '부스터', '불꽃', '불꽃포켓몬', 0.9, 25, '체내에 불꽃 주머니를 가지고 있다. 싸움이 시작되기 직전에는 체온이 900도까지 올라간다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '폴리곤', '노말', '가상포켓몬', 0.8, 36.5, '세계에서 처음으로 인공적으로 만들어 낸 포켓몬이다. 전자 공간을 이동할 수 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '암나이트', '바위, 물', '소용돌이포켓몬', 0.4, 7.5, '현대의 우수한 과학 기술로 화석에서 부활한 포켓몬이다. 고대의 바다를 헤엄치고 있었다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '암스타', '바위, 물', '소용돌이포켓몬', 1, 35, '나선형의 껍질이 너무 커져 버린 것이 원인으로 멸종했다고 여겨지고 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '투구', '바위, 물', '껍질포켓몬', 0.5, 11.5, '3억 년 전에 모래 해변에서 살고 있었던 것으로 추측된다. 단단한 껍질이 몸을 보호한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '투구푸스', '바위,	물', '껍질포켓몬', 1.3, 40.5, '투구푸스의 먹이가 육상 생활을 시작했기 때문에 투구푸스 역시 육지에 올라온 것으로 추측된다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '프테라', '바위, 비행', '화석포켓몬', 1.8, 59, '공룡 시대의 넓은 하늘을 날아다녔던 포켓몬이다. 톱 같은 이빨을 가지고 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '잠만보', '노말', '졸음포켓몬', 2.1, 79, '곰팡이가 피어 있거나 상했어도 괜찮다. 잠만보의 위는 무엇이든 소화시킬 수 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '프리져', '얼음, 비행', '냉동포켓몬', 1.7, 55.4, '전설의 새포켓몬이다. 공기 중의 수분을 얼려 눈보라를 만들어 낼 수 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '썬더', '전기, 비행', '전기포켓몬', 1.6, 52.6, '번개 구름 안에 있다고 전해지는 전설의 포켓몬이다. 번개를 자유로이 조종한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '파이어', '불꽃, 비행', '화염포켓몬', 2, 60, '전설의 새포켓몬 중의 1마리다. 파이어가 모습을 보이면 봄이 찾아온다고 전해진다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '미뇽', '드래곤', '드래곤포켓몬', 1.8, 3.3, '목격자가 적기 때문에 환상의 포켓몬이라고 불렸다. 탈피한 껍질이 발견되고 있다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '신뇽', '드래곤', 	'드래곤포켓몬', 4, 16.5, '전신이 오라에 둘러싸일 때는 주위 날씨가 완전히 바뀐다. 바다나 호수에서 산다고 한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '망나뇽', '드래곤,	비행', '드래곤포켓몬', 2.2, 210, '넓은 바다의 어딘가에 거처가 있다고 전해진다. 난파한 배를 육지까지 이끌어 준다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '뮤츠', '에스퍼', '유전포켓몬', 2, 122, '뮤의 유전자를 재구성해서 만들어졌다. 포켓몬 중에서 가장 난폭한 마음을 가지고 있다고 한다.', 0);
INSERT INTO POKEMON VALUES(SEQ_PKNO.NEXTVAL, '뮤', '에스퍼', '신종포켓몬', 0.4, 4, '모든 기술을 사용하기 때문에 포켓몬의 조상이라고 생각하는 학자가 많다.', 0);

COMMIT;