DROP TABLE POKEMON;


CREATE TABLE POKEMON(
PKNO NUMBER PRIMARY KEY,
PKNAME VARCHAR2(30) NOT NULL UNIQUE,
PKTYPE VARCHAR2(30) NOT NULL,
PKCLASS VARCHAR2(30) NOT NULL,
PKHEIGHT NUMBER,
PKWEIGHT NUMBER,
PKDETAIL VARCHAR2(100)
);

CREATE SEQUENCE SEQ_PKNO
NOCACHE;

INSERT INTO POKEMON 
VALUES();


UPDATE MEMBER
SET USERPWD = '',
    EMAIL = '',
    PHONE = '',
    ADDRESS = ''
WHERE USERID = '';

DELETE FROM MEMBER
WHERE USERID = '';


SELECT DISTINCT PKTYPE FROM POKEMON;