DROP TABLE POKEMON;

DROP TABLE TRAINER;

DROP SEQUENCE SEQ_PKNO;

CREATE TABLE TRAINER(
TRNO NUMBER UNIQUE,
TRID VARCHAR2(30) PRIMARY KEY,
TRPWD VARCHAR2(30) NOT NULL,
TRNAME VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE POKEMON(
PKNO NUMBER PRIMARY KEY,
PKNAME VARCHAR2(30) NOT NULL UNIQUE,
PKTYPE VARCHAR2(30) NOT NULL,
PKCLASS VARCHAR2(30) NOT NULL,
PKHEIGHT NUMBER,
PKWEIGHT NUMBER,
PKDETAIL VARCHAR2(200),
TRNO NUMBER REFERENCES TRAINER(TRNO)
);

CREATE SEQUENCE SEQ_PKNO
NOCACHE;



SELECT DISTINCT PKTYPE FROM POKEMON;

INSERT INTO POKEMON VALUES(25, '피카츄', '전기', '쥐포켓몬', 0.4, 6.0, '숲속에서 동료와 산다. 볼의 양쪽에 있는 전기 주머니에 전기를 모아 둔다.', 1);
INSERT INTO POKEMON VALUES(95, '롱스톤', '바위', '돌뱀포켓몬', 8.8, 210.0, '몸을 구부리고 비틀어서 땅속을 파고 지나가는 소리는 아주 먼 곳까지 울려퍼진다.', 2);
INSERT INTO POKEMON VALUES(54, '고라파덕', '물', '오리포켓몬', 0.8, 19.6, '이상한 힘을 간직하고 있지만 사용했던 기억이 없으므로 항상 고개를 갸웃거리고 있다.', 3);



INSERT INTO TRAINER VALUES(1, 'user01', 'pass01', '한지우');
INSERT INTO TRAINER VALUES(2, 'user02', 'pass02', '웅');
INSERT INTO TRAINER VALUES(3, 'user03', 'pass03', '이슬');