SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열"
FROM TB_DEPARTMENT;

SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN, 8,1) = '2' AND DEPARTMENT_NO = 001 AND ABSENCE_YN = 'Y';

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO = 'A513079' 
OR STUDENT_NO = 'A513090' 
OR STUDENT_NO = 'A513091' 
OR STUDENT_NO = 'A513110' 
OR STUDENT_NO = 'A513119'
ORDER BY STUDENT_NAME DESC;

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;


SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY 1;

SELECT STUDENT_NO, STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '전주%' 
AND EXTRACT(YEAR FROM ENTRANCE_DATE) = 2002 
AND ABSENCE_YN ='N';


SELECT * FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;

SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", TO_CHAR(ENTRANCE_DATE, 'RRRR-MM-DD') AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY 입학년도;

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

SELECT PROFESSOR_NAME, PROFESSOR_SSN, EXTRACT(YEAR FROM SYSDATE),(EXTRACT(YEAR FROM (TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'YYMMDD'))) - 100) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8,1) = 1
ORDER BY 2;



SELECT PROFESSOR_NAME AS "교수이름", 
EXTRACT(YEAR FROM SYSDATE) - (EXTRACT(YEAR FROM (TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'YYMMDD'))) - 100) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8,1) = 1
ORDER BY 2;

SELECT SUBSTR(PROFESSOR_NAME, 2,2) AS "이름"
FROM TB_PROFESSOR;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM (TO_DATE(SUBSTR(ENTRANCE_DATE, 1,8)))) - EXTRACT(YEAR FROM (TO_DATE(SUBSTR(STUDENT_SSN, 1,6)))) NOT BETWEEN 18 AND 19;

SELECT TO_CHAR(TO_DATE('20201225'), 'DAY') FROM DUAL;

SELECT 
EXTRACT (YEAR FROM (TO_DATE('99/10/11','YY/MM/DD'))) AS "2099년",
EXTRACT (MONTH FROM (TO_DATE('99/10/11','YY/MM/DD'))) AS "2099월",
EXTRACT (DAY FROM (TO_DATE('99/10/11','YY/MM/DD'))) AS "2099일",

EXTRACT (YEAR FROM (TO_DATE('49/10/11','YY/MM/DD'))) AS "2049년",
EXTRACT (MONTH FROM (TO_DATE('49/10/11','YY/MM/DD'))) AS "2049월",
EXTRACT (DAY FROM (TO_DATE('49/10/11','YY/MM/DD'))) AS "2049일",

EXTRACT (YEAR FROM (TO_DATE('99/10/11','RR/MM/DD'))) AS "1999년",
EXTRACT (MONTH FROM (TO_DATE('99/10/11','RR/MM/DD'))) AS "1999월",
EXTRACT (DAY FROM (TO_DATE('99/10/11','RR/MM/DD'))) AS "1999일",

EXTRACT (YEAR FROM (TO_DATE('49/10/11','RR/MM/DD'))) AS "2049년",
EXTRACT (MONTH FROM (TO_DATE('49/10/11','RR/MM/DD'))) AS "2049월",
EXTRACT (DAY FROM (TO_DATE('49/10/11','RR/MM/DD'))) AS "2049일"
FROM DUAL;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE NOT STUDENT_NO LIKE 'A%';

SELECT ROUND(AVG(POINT), 1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

SELECT DEPARTMENT_NO, COUNT(DEPARTMENT_NO)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

SELECT EXTRACT(YEAR FROM (TO_DATE(TERM_NO, 'YYMM'))) AS "년도"
, ROUND(AVG(POINT), 1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY EXTRACT(YEAR FROM (TO_DATE(TERM_NO, 'YYMM')))
ORDER BY 1;

SELECT *
FROM TB_STUDENT;


SELECT DEPARTMENT_NO AS "학과코드명", COUNT(DECODE (ABSENCE_YN, 'Y',0)) AS "휴학생 수"
--COUNT(ABSENCE_YN)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
--HAVING COUNT(ABSENCE_YN) >= 0
ORDER BY 1;

SELECT STUDENT_NAME AS "동일이름", COUNT(STUDENT_NAME) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY 1;

SELECT * 
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';
SELECT  NVL(SUBSTR(TERM_NO,1,4), ' ') AS "년도", NVL(SUBSTR(TERM_NO,5,2), ' ') AS "학기", ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113' 
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2));


